
# catalog-info.yml
# This file contains metadata for backstage
# Read more about available fields and annotations:
# https://github.com/tradeshift/backstage
#
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: puppet-module-nexus3_rest
  description: |
    puppet-module-nexus3_rest module
  annotations:
    github.com/project-slug: Tradeshift/puppet-module-nexus3_rest # GitHub project name

spec:
  type: other
  owner: platform-ops
  lifecycle: experimental